USE [master];
GO

IF EXISTS (SELECT name FROM sys.databases WHERE name = N'IDontKnowSQL')
BEGIN
  ALTER DATABASE [IDontKnowSQL] SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
  DROP DATABASE IF EXISTS [IDontKnowSQL];
END
ELSE
BEGIN
    PRINT 'Database IDontKnowSQL does not exist.';
END;
GO

CREATE DATABASE IDontKnowSQL;
GO
USE IDontKnowSQL;
GO
DROP TABLE IF EXISTS BigTable;
GO
CREATE TABLE BigTable (col1 INT PRIMARY KEY CLUSTERED, col2 CHAR(5000) NOT NULL);
GO
SET NOCOUNT ON;
GO
BEGIN TRAN;
GO
DECLARE @i INT;
SET @i = 0;
WHILE (@i < 10000)
BEGIN
	INSERT INTO BigTable VALUES (@i, 'Who said I can''t use SQL Server 2025?');
	SET @i = @i + 1;
END
GO
COMMIT TRAN;
GO
SET NOCOUNT OFF;
GO