CREATE TABLE [STAGING].[CUSTOMER]
( 
	[C_CUSTKEY] [decimal](38,18)  NULL,
	[C_NAME] [nvarchar](4000)  NULL,
	[C_ADDRESS] [nvarchar](4000)  NULL,
	[C_NATIONKEY] [decimal](38,18)  NULL,
	[C_PHONE] [nvarchar](4000)  NULL,
	[C_ACCTBAL] [decimal](38,18)  NULL,
	[C_MKTSEGMENT] [nvarchar](4000)  NULL,
	[C_COMMENT] [nvarchar](4000)  NULL
)
WITH
(
	DISTRIBUTION = ROUND_ROBIN,
	--CLUSTERED COLUMNSTORE INDEX
	HEAP
);
GO
--TRUNCATE TABLE STAGING.CUSTOMER;
COPY INTO STAGING.CUSTOMER
(C_CUSTKEY 1, C_NAME 2, C_ADDRESS 3, C_NATIONKEY 4, C_PHONE 5, C_ACCTBAL 6, C_MKTSEGMENT 7, C_COMMENT 8)
FROM 'https://synapsedemopp1adls.dfs.core.windows.net/datalake/raw/demo/TPCH_SF100/CUSTOMER/*'
WITH
(
	FILE_TYPE = 'PARQUET'
	,MAXERRORS = 0
	,COMPRESSION = 'snappy'
	,IDENTITY_INSERT = 'OFF'
);
GO

SELECT FORMAT(COUNT(*), '#,#') FROM [STAGING].[CUSTOMER];

