-- Use CTAS to recreate table and narrow data types

DROP TABLE [TPCH].[LINEITEM];
GO
CREATE TABLE [TPCH].[LINEITEM] (
	L_ORDERKEY,
	L_PARTKEY,
	L_SUPPKEY,
	L_LINENUMBER,
	L_QUANTITY,
	L_EXTENDEDPRICE,
	L_DISCOUNT,
	L_TAX,
	L_RETURNFLAG,
	L_LINESTATUS,
	L_SHIPDATE,
	L_COMMITDATE,
	L_RECEIPTDATE,
	L_SHIPINSTRUCT,
	L_SHIPMODE,
	L_COMMENT
)
WITH (
	DISTRIBUTION = ROUND_ROBIN,
	CLUSTERED COLUMNSTORE INDEX
)
AS
SELECT 
	ISNULL(CAST([L_ORDERKEY] AS [bigint]), 0),
	ISNULL(CAST([L_PARTKEY] AS [bigint]), 0),
	ISNULL(CAST([L_SUPPKEY] AS [bigint]), 0),
	ISNULL(CAST([L_LINENUMBER] AS [int]), 0),
	CAST([L_QUANTITY] AS [decimal](18, 0)),
	CAST([L_EXTENDEDPRICE] AS [decimal](18, 0)),
	CAST([L_DISCOUNT] AS [decimal](18, 0)),
	CAST([L_TAX] AS [decimal](18, 0)),
	CAST([L_RETURNFLAG] AS [char](1)),
	CAST([L_LINESTATUS] AS [char](1)),
	CAST([L_SHIPDATE] AS [date]),
	CAST([L_COMMITDATE] AS [date]),
	CAST([L_RECEIPTDATE] AS [date]),
	CAST([L_SHIPINSTRUCT] AS [char](25)),
	CAST([L_SHIPMODE] AS [char](10)),
	CAST([L_COMMENT] AS [varchar](44))
FROM STAGING.LINEITEM;
GO

-- Performance benchmark (TPC-H Query #1)

DBCC DROPCLEANBUFFERS;
DBCC FREEPROCCACHE;
DBCC DROPRESULTSETCACHE;
SET RESULT_SET_CACHING OFF;
GO
SELECT
    L_RETURNFLAG,
    L_LINESTATUS,
    SUM(L_QUANTITY) AS SUM_QTY,
    SUM(L_EXTENDEDPRICE) AS SUM_BASE_PRICE,
    SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT)) AS SUM_DISC_PRICE,
    SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT) * (1 + L_TAX)) AS SUM_CHARGE,
    AVG(L_QUANTITY) AS AVG_QTY,
    AVG(L_EXTENDEDPRICE) AS AVG_PRICE,
    AVG(L_DISCOUNT) AS AVG_DISC,
    COUNT(*) AS COUNT_ORDER
FROM
    STAGING.LINEITEM
WHERE
    L_SHIPDATE <= DATEADD(day,-90,'1998-12-01')
GROUP BY
    L_RETURNFLAG,
    L_LINESTATUS
ORDER BY
    L_RETURNFLAG,
    L_LINESTATUS;
GO

--

DBCC DROPCLEANBUFFERS;
DBCC FREEPROCCACHE;
DBCC DROPRESULTSETCACHE;
SET RESULT_SET_CACHING OFF;
GO
SELECT
    L_RETURNFLAG,
    L_LINESTATUS,
    SUM(L_QUANTITY) AS SUM_QTY,
    SUM(L_EXTENDEDPRICE) AS SUM_BASE_PRICE,
    SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT)) AS SUM_DISC_PRICE,
    SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT) * (1 + L_TAX)) AS SUM_CHARGE,
    AVG(L_QUANTITY) AS AVG_QTY,
    AVG(L_EXTENDEDPRICE) AS AVG_PRICE,
    AVG(L_DISCOUNT) AS AVG_DISC,
    COUNT(*) AS COUNT_ORDER
FROM
    TPCH.LINEITEM
WHERE
    L_SHIPDATE <= DATEADD(day,-90,'1998-12-01')
GROUP BY
    L_RETURNFLAG,
    L_LINESTATUS
ORDER BY
    L_RETURNFLAG,
    L_LINESTATUS;
GO