start snowsql -c dcpl -f TestSF.sql
start snowsql -c dcpl -f TestSF.sql
start snowsql -c dcpl -f TestSF.sql
start snowsql -c dcpl -f TestSF.sql
start snowsql -c dcpl -f TestSF.sql
start snowsql -c dcpl -f TestSF.sql
start snowsql -c dcpl -f TestSF.sql
start snowsql -c dcpl -f TestSF.sql
start snowsql -c dcpl -f TestSF.sql
start snowsql -c dcpl -f TestSF.sql
start snowsql -c dcpl -f TestSF.sql
start snowsql -c dcpl -f TestSF.sql
start snowsql -c dcpl -f TestSF.sql
start snowsql -c dcpl -f TestSF.sql
start snowsql -c dcpl -f TestSF.sql
start snowsql -c dcpl -f TestSF.sql
start snowsql -c dcpl -f TestSF.sql
start snowsql -c dcpl -f TestSF.sql
start snowsql -c dcpl -f TestSF.sql
start snowsql -c dcpl -f TestSF.sql
start snowsql -c dcpl -f TestSF.sql
start snowsql -c dcpl -f TestSF.sql
start snowsql -c dcpl -f TestSF.sql
start snowsql -c dcpl -f TestSF.sql
start snowsql -c dcpl -f TestSF.sql
start snowsql -c dcpl -f TestSF.sql
start snowsql -c dcpl -f TestSF.sql
start snowsql -c dcpl -f TestSF.sql
start snowsql -c dcpl -f TestSF.sql
start snowsql -c dcpl -f TestSF.sql
start snowsql -c dcpl -f TestSF.sql
start snowsql -c dcpl -f TestSF.sql
pause